version: "3.7"
services:
  frontend:
    image: janejavannie/rent-frontend
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
    build:
      context: ./WebClient
    # volumes:
    #   - ./WebClient/build:/usr/share/nginx/html/app

  backend:
    image: janejavannie/rent-backend
    build:
      context: ./Api
    ports:
      - "90:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ConnectionStrings:Default=Host=postgres;Port=5432;Database=rent;Username=postgres;Password=postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  frontend:
  postgres_data:
