version: "3.7"
services:
  frontend:
    container_name: frontend
    build:
      context: ./WebClient
    volumes:
      - frontend:/app

  backend:
    container_name: backend
    build:
      context: ./Api
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=production
      - ConnectionStrings:Default=Host=postgres;Port=5432;Database=rent;Username=postgres;Password=postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
    depends_on:
      - backend
    volumes:
      - frontend:/usr/share/nginx/html/app:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  frontend:
  postgres_data:
