name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: image

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker-compose push

      - name: Copy docker-compose.yaml
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-12-144-198.us-east-2.compute.amazonaws.com
          username: ec2-user
          port: 22
          key: ${{ secrets.AWS_KEY }}
          source: "docker-compose.yaml"
          target: "~/"
          
      - name: Run docker stack deploy
        uses: appleboy/ssh-action@master
        with:
          host: ec2-3-12-144-198.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            docker stack deploy -c docker-compose.yaml rent
