name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
#     tags:
#       - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker-compose push
          
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: http://ec2-3-16-114-243.us-east-2.compute.amazonaws.com/
          username: ec2-user
          port: 22
          key: ${{ secrets.AWS_KEY }}
          source: "docker-compose.yaml"
          target: "~/docker-compose.yaml"
          
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: http://ec2-3-16-114-243.us-east-2.compute.amazonaws.com/
          username: ec2-user
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            docker stack deploy -c docker-compose.yaml rent
